spring:
  application:
    name: ji-ai-agent
  ai:
    vertex:
      ai:
        gemini:
          project-id: ji-ai-agent
          location: us-central1
          chat:
            options:
              model:  gemini-2.5-flash-lite
              temperature: 0.7
        embedding:
          project-id: ji-ai-agent
          location: us-central1
          text:
            options:
              model: text-embedding-005
      mcp:
        client:
          sse:
            connections:
              server1:
                url: ${MCP_IMAGE_SEARCH_URL:http://localhost:8127}
#          stdio:
#            servers-configuration: classpath:mcp-servers.json
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 768
        distance-type: COSINE_DISTANCE
        initialize-schema: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_project
    username: postgres
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true
# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaohang.jiaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language:en-US
logging:
  level:
    org.springframework.ai: DEBUG

# application.yml
search:
  api-key: ${SEARCH_API_KEY}