spring:
  application:
    name:ji-ai-agent
  google:
    api:
      key: ${API_KEY}
      model: gemini-2.0-flash
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaohang.jiaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language:en-US