spring:
  application:
    name: ji-image-search-mcp-server
  profiles:
    active: sse
server:
 port: ${PORT:8127}
#   port: 8127
pexels:
  api-key: ${PEXELS_API_KEY:qFB5v0CP9hvaxXwN96PiXPXGEu9MidnmTwDLG3db0MBUmS5Tif2yZd2u}