package com.xiaohang.jiaiagent.agent.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;

/**
 * Represents a complete execution plan decomposed from a user's complex task.
 *
 * <p>The plan captures the PlannerAgent's output: a structured list of steps
 * with clear dependencies, tool assignments, and execution order. This model
 * serves as the contract between the planning phase and the execution phase.
 *
 * <p>The plan lifecycle:
 * <ol>
 *   <li>{@code CREATED} — plan generated by PlannerAgent</li>
 *   <li>{@code APPROVED} — user or supervisor reviews and approves</li>
 *   <li>{@code EXECUTING} — steps are being executed</li>
 *   <li>{@code COMPLETED} — all steps finished successfully</li>
 *   <li>{@code FAILED} — one or more steps failed</li>
 * </ol>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExecutionPlan {

    /**
     * Unique identifier for this plan (UUID).
     */
    private String planId;

    /**
     * The original user request that triggered this plan.
     */
    private String originalTask;

    /**
     * The LLM-generated high-level summary of the plan.
     */
    private String summary;

    /**
     * Ordered list of steps to execute. Steps should be processed in order,
     * respecting dependency constraints defined in each step.
     */
    private List<PlanStep> steps;

    /**
     * Total number of steps in this plan.
     */
    private int totalSteps;

    /**
     * Number of steps that completed successfully.
     */
    private int completedSteps;

    /**
     * Number of steps that failed.
     */
    private int failedSteps;

    /**
     * Current lifecycle state of the plan.
     */
    private PlanStatus status;

    /**
     * Timestamp when the plan was generated.
     */
    private Instant createdAt;

    /**
     * Timestamp when plan execution started.
     */
    private Instant startedAt;

    /**
     * Timestamp when plan execution finished (success or failure).
     */
    private Instant finishedAt;

    /**
     * Total estimated time in seconds (filled by PlannerAgent).
     */
    private Integer estimatedDurationSeconds;

    /**
     * Tags or categories for this plan (e.g., "research", "code", "analysis").
     */
    private List<String> tags;

    public enum PlanStatus {
        /**
         * Plan has been generated but not yet approved for execution.
         */
        CREATED,

        /**
         * Plan approved, execution in progress.
         */
        EXECUTING,

        /**
         * All steps completed successfully.
         */
        COMPLETED,

        /**
         * One or more steps failed and the plan could not continue.
         */
        FAILED,

        /**
         * Plan was cancelled by the user or supervisor.
         */
        CANCELLED,

        /**
         * Plan has been re-planned after a step failure.
         */
        RE_PLANNED
    }

    /**
     * Returns the number of steps that have not yet been attempted.
     */
    public int getPendingSteps() {
        return (int) steps.stream()
                .filter(s -> s.getStatus() == PlanStep.StepStatus.PENDING
                        || s.getStatus() == null)
                .count();
    }

    /**
     * Returns the overall completion percentage (0–100).
     */
    public int getProgressPercent() {
        if (totalSteps == 0) return 0;
        return (int) ((completedSteps + failedSteps) * 100.0 / totalSteps);
    }

    /**
     * Returns true if all steps are in a terminal state (completed, failed, or skipped).
     */
    public boolean isFinished() {
        return completedSteps + failedSteps >= totalSteps;
    }
}
